apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-producto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-producto
  template:
    metadata:
      labels:
        app: microservicio-producto
    spec:
      containers:
        - name: app
          image: microservicio-producto:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio-producto
spec:
  selector:
    app: microservicio-producto
  ports:
    - port: 8070
      targetPort: 8070
  type: LoadBalancer